### ISSUE TITLE
tensorflow version

### ISSUE THREAD

**Issue by mia12-12** [alirezatwk/Convolutional-Neural-Network-Based-Image-Watermarking-using-Discrete-Wavelet-Transform#3]
hello,Dear author
 Thank you for your work! Is there a way to replace the Tensorflow version? Because the cuda10.2 I installed cannot match the Tensorflow of 2.5.0, if I reinstall a higher version of cuda, I will not be able to complete other experiments. Any reply will be appreciated!

**Comment by alirezatwk** [comment]
Hello, thank you for your interest in our work. 
We are sorry to hear that you have problems with the Tensorflow version. We used Tensorflow 2.5.0 because it had some features that we needed for our experiments that were not available in the newer versions. 
We are not planning to update our code to make it compatible with the newer versions of Tensorflow. We suggest that you either use a different environment for running our code, such as a virtual environment or a docker container, or try to modify the code yourself to adapt it to the newer versions of Tensorflow. We apologize for any inconvenience this may cause you.
